cmd = '''python -u runner_london.py
        --model_type {model_type}
        --latent_model {latent_model}
        --grid_size {grid_size}
        --gp {gp} 
        --kernel {kernel}
        --time_kernel {time_kernel}
        --fold {fold}
        --epochs {epochs}
        --lr {lr}
        --optimizer {optimizer} 
        --mode {mode} 
        --seed {seed} 
        --n_inducing {n_inducing}
        --features {features}
        --rootdir {rootdir}
        '''

# arguments to be handled internally: seed, features

[[exp]]
uid = './{rootdir}/{model_type}-{gp}-{latent_model}-grid-{grid_size}-ind-{n_inducing}-{kernel}-time-{time_kernel}/fold-{fold}/opt-{optimizer}-epochs-{epochs}-lr-{lr}'
rootdir = "results_dummy_london"
fold = 0

# seed = 0
# mode = "test"

seed = 0
mode = "train"                                  # ["train", "test"]

gp = "sparse"                                   # ["exact", "sparse"]
model_type = "e"                                # ["e", "l", "ls", "lso"]
latent_model = "heinonen"                       # ["heinonen", "delta", "gaussian", "plagemann"]
grid_size = 100
features = '["latitude","longitude","temperature","pressure","humidity","wind_speed","delta_t"]'
n_inducing = 1000
epochs = 500
kernel = "matern32"
time_kernel = "matern32"
lr = 0.1
optimizer = "lbfgsb"                            # ["adam", "lbfgsb", "bfgs"]

[flags]
restart = true
num_proc = 1
gpu_indices = ["0"]